// lib/lint/kb-loader.ts
// Memoized loader for the consumer's knowledge-base registries. The loader
// reads each registry JSON exactly once per process; subsequent calls return
// the cached value. KB files are static-ish (regenerated by the cron); no
// invalidation needed within a single lint run.
import { readFileSync, existsSync } from "node:fs";
import path from "node:path";

export interface VariableEntry {
  readonly key: string;
  readonly name: string;
  readonly resolvedType?: "COLOR" | "FLOAT" | "STRING" | "BOOLEAN";
  readonly valuesByMode?: Record<string, unknown>;
  readonly status?: "active" | "deprecated";
  // additional fields tolerated but not used by these functions
}

export interface ComponentEntry {
  readonly key: string;
  readonly name: string;
  readonly status?: "stable" | "beta" | "deprecated" | "experimental";
}

export interface KBSnapshot {
  readonly variableByName: Map<string, VariableEntry>;
  readonly componentByName: Map<string, ComponentEntry>;
  readonly textStyleByName: Map<string, { key: string; name: string }>;
}

const cache = new Map<string, KBSnapshot | null>();

function safeReadJson<T>(p: string): T | null {
  try {
    return JSON.parse(readFileSync(p, "utf-8")) as T;
  } catch {
    return null;
  }
}

/** Load the KB registries from <cwd>/<kbPath>. Returns null if no registries dir exists. */
export function loadKB(cwd: string, kbPath = "bridge-ds/knowledge-base"): KBSnapshot | null {
  const key = `${cwd}::${kbPath}`;
  if (cache.has(key)) return cache.get(key) ?? null;

  const regDir = path.join(cwd, kbPath, "registries");
  if (!existsSync(regDir)) {
    cache.set(key, null);
    return null;
  }

  // variables.json may have multiple shapes — handle both:
  //   { version, generatedAt, variables: [...] }   (v1 schema)
  //   { meta: {...}, variables: { byCategory: [...] } }  (legacy MCP shape)
  const variableByName = new Map<string, VariableEntry>();
  const varsRaw = safeReadJson<{ variables?: unknown }>(path.join(regDir, "variables.json"));
  const varsList: VariableEntry[] = Array.isArray(varsRaw?.variables)
    ? (varsRaw.variables as VariableEntry[])
    : [];
  for (const v of varsList) {
    if (v?.name) variableByName.set(stripTokenPrefix(v.name), v);
  }

  const componentByName = new Map<string, ComponentEntry>();
  const compsRaw = safeReadJson<{ components?: unknown }>(path.join(regDir, "components.json"));
  const compsList: ComponentEntry[] = Array.isArray(compsRaw?.components)
    ? (compsRaw.components as ComponentEntry[])
    : [];
  for (const c of compsList) {
    if (c?.name) componentByName.set(c.name, c);
  }

  const textStyleByName = new Map<string, { key: string; name: string }>();
  const stylesRaw = safeReadJson<{ styles?: unknown }>(path.join(regDir, "text-styles.json"));
  const stylesList = Array.isArray(stylesRaw?.styles)
    ? (stylesRaw.styles as { key: string; name: string }[])
    : [];
  for (const s of stylesList) {
    if (s?.name) textStyleByName.set(s.name, s);
  }

  const snapshot: KBSnapshot = { variableByName, componentByName, textStyleByName };
  cache.set(key, snapshot);
  return snapshot;
}

/** Reset the cache. Used in tests; not exported beyond the test boundary. */
export function _resetKBCache(): void {
  cache.clear();
}

/** Strip the leading `$` from a token reference like `$color/bg/surface/subtle`. */
function stripTokenPrefix(name: string): string {
  return name.startsWith("$") ? name.slice(1) : name;
}
